/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'nemagfx_tp_rotating_zoom' 
 * Target:  'nemagfx_tp_rotating_zoom' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "apollo510.h"



#endif /* RTE_COMPONENTS_H */
